#!/bin/sh
#   THIS SCRIPT FILE WILL BE USED TO COMPILE YOUR RIX FILES

RIX_HOME=${RIX_HOME:-.}
RIX_FILE=${1}
#Grab the rix file's fullpath and directory
RIX_FILE_PATH=$( readlink -f "$RIX_FILE" )
RIX_FILE_DIR=$( dirname "$RIX_FILE" )

${RIX_HOME}/rixc -q -o ${RIX_FILE_PATH} ${RIX_FILE}
if [ $? -eq 0 ]; then
	chmod +x ${RIX_FILE}.sh
	${RIX_FILE}.sh
fi
shift
${RIX_FILE}.out $@
rm ${RIX_FILE}.out 
rm ${RIX_FILE}.c 
rm ${RIX_FILE}.h 
rm ${RIX_FILE}.sh 
rm ${RIX_FILE}.log
rm "rix_temp_file.rit"

echo "...END..."
